{
    "name": """Customer Chat""",
    "summary": """Be in touch with your partners via any supported channels (Telegram, WhatsApp, Viber, etc.)""",
    "category": "Marketing",
    "images": ["static/description/messengers_image.png"],
    "version": "17.0.2.0.0",
    "application": False,
    "author": "UnitSoft",
    "support": "",
    "website": "https://unitsoft.com.ua/",
    "license": "LGPL-3",
    "price": 0,
    "currency": "EUR",
    "depends": ["mail"],
    "external_dependencies": {"python": [], "bin": []},
    "data": [],
    "post_load": None,
    "pre_init_hook": None,
    "post_init_hook": None,
    "uninstall_hook": None,
    "auto_install": False,
    "installable": True,
}
